
import __ASTRO_IMAGE_IMPORT_Bc6d1 from "../main-author/avatar.png?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_XY0Aq from "../pencil-case-full-of-stubby-pencils/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fpencil-case-full-of-stubby-pencils%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Zo1CdX from "../people-ask-how-we-survived-without-helmets-and-knee-pads/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fpeople-ask-how-we-survived-without-helmets-and-knee-pads%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z10Wgt1 from "../summers-were-hot-sticky/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fsummers-were-hot-sticky%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_292bWt from "../tailwind-gradient-underline/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1wxBlc from "../example-one/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-one%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_f3HSB from "../example-two/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-two%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1fH1Ye from "../tsconfig-paths-setup/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Ftsconfig-paths-setup%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZK1mN6 from "../tasmania-travel-guide/heroImage.gif?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftasmania-travel-guide%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_VU65f from "../chalk-scraping-across-the-board/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fchalk-scraping-across-the-board%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_c7b6Q from "../tailwind-gradient-underline/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Ftailwind-gradient-underline%2Findex.mdx";
export default new Map([["../main-author/avatar.png?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Bc6d1], ["../pencil-case-full-of-stubby-pencils/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fpencil-case-full-of-stubby-pencils%2Findex.mdx", __ASTRO_IMAGE_IMPORT_XY0Aq], ["../people-ask-how-we-survived-without-helmets-and-knee-pads/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fpeople-ask-how-we-survived-without-helmets-and-knee-pads%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Zo1CdX], ["../summers-were-hot-sticky/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fsummers-were-hot-sticky%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z10Wgt1], ["../tailwind-gradient-underline/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx", __ASTRO_IMAGE_IMPORT_292bWt], ["../example-one/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-one%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1wxBlc], ["../example-two/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-two%2Findex.mdx", __ASTRO_IMAGE_IMPORT_f3HSB], ["../tsconfig-paths-setup/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Ftsconfig-paths-setup%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1fH1Ye], ["../tasmania-travel-guide/heroImage.gif?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftasmania-travel-guide%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZK1mN6], ["../chalk-scraping-across-the-board/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fchalk-scraping-across-the-board%2Findex.mdx", __ASTRO_IMAGE_IMPORT_VU65f], ["../tailwind-gradient-underline/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Ftailwind-gradient-underline%2Findex.mdx", __ASTRO_IMAGE_IMPORT_c7b6Q]]);
		